#!/bin/sh

# check whether all input files will be available:
if [ ! -e test/lib/gromacs/multi/topol.tpr ]; then
    echo "This example script must be run from within the copernicus base directory"
    exit 1
fi

if [ $# -lt 1 ]; then
    echo "Usage:"
    echo "runtest projectname"
    exit 1
fi
projectname=$1


# start the project
./cpcc start $projectname
# import the gromacs module with grompp and mdrun functions
./cpcc import gromacs
# add the grompp and mdrun function instances
./cpcc instance gromacs::mdrun_multi mdrun_multi

# activate the function instance
./cpcc activate 

# start a transaction: all the 'set' and 'connect' commands following this
# will be executed as one atomic operation upon the cpcc commit command.
./cpcc transact
# connect the tpr output of grompp to the tpr input of mdrun

#NOTE WE CAN LOOP OVER THIS
./cpcc set-file mdrun_multi:in.tpr[+] test/lib/gromacs/multi/topol.tpr
#./cpcc set-file mdrun_multi:in.tpr[+] test/lib/gromacs/multi/topol.tpr
 
./cpcc commit

