#!/bin/sh

# check whether all input files will be available:
if [ ! -e cpc/test/lib/gromacs/multi//conf.gro ]; then
    echo "This example script must be run from within the copernicus base directory"
    exit 1
fi

# start the project
./cpcc start test
# import the gromacs module with grompp and mdrun functions
./cpcc import gromacs
# add the grompp and mdrun function instances
./cpcc instance gromacs::grompp_multi grompp_multi
#./cpcc instance gromacs::mdrun mdrun
# activate the function instance
./cpcc activate 

# start a transaction: all the 'set' and 'connect' commands following this
# will be executed as one atomic operation upon the cpcc commit command.
./cpcc transact
# connect the tpr output of grompp to the tpr input of mdrun
#./cpcc connect grompp:out.tpr mdrun:in.tpr
# set the grompp inputs

#NOTE WE CAN LOOP OVER THIS
./cpcc set-file grompp_multi:in.conf[+] cpc/test/lib/gromacs/multi/conf.gro
./cpcc set-file grompp_multi:in.mdp[+]  cpc/test/lib/gromacs/multi/grompp.mdp
./cpcc set-file grompp_multi:in.top[+]  cpc/test/lib/gromacs/multi/topol.top
# 
./cpcc set-file grompp_multi:in.conf[+] cpc/test/lib/gromacs/multi/conf.gro
./cpcc set-file grompp_multi:in.mdp[+]  cpc/test/lib/gromacs/multi/grompp.mdp
./cpcc set-file grompp_multi:in.top[+]  cpc/test/lib/gromacs/multi/topol.top



#NOTE these ones cannot be set with +
#./cpcc set grompp_multi:in.settings[0].name nsteps
#./cpcc set grompp_multi:in.settings[0].value 10000
#./cpcc set grompp_multi:in.settings[1].name integrator
#./cpcc set grompp_multi:in.settings[1].value md
# and commit this set of updates


./cpcc commit

