#!/usr/bin/env python

# This file is part of Copernicus
# http://www.copernicus-computing.org/
# 
# Copyright (C) 2011, Sander Pronk, Iman Pouya, Erik Lindahl, and others.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published 
# by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import sys
import os
import math
import os.path
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

import cpc.dataflow
from cpc.dataflow import StringValue
from cpc.dataflow import FloatValue
from cpc.dataflow import IntValue
from cpc.dataflow import RecordValue
from cpc.dataflow import ArrayValue


class FEError(cpc.dataflow.ApplicationError):
    pass


def g_rama_multi(inp, out):
    pers=cpc.dataflow.Persistence(os.path.join(inp.persistentDir,
                                               "persistent.dat"))
    insts=pers.get('insts')
    if insts is None:
        insts=[]
    confs=inp.getInput('confs')

    #while len(confs) > len(insts):
    for i in range(len(confs)):
        while len(insts) < i+1:
            insts.append(0)
            sys.stderr.write('insts[%d]: %d elements\n'%(len(insts)-1,
                                                         insts[len(insts)-1]))
        sconfs=inp.getInput('confs[%d]'%i)
        while len(sconfs) > insts[i]:
            j=insts[i]
            instname='g_rama_%d_%d'%(i,j)
            out.addInstance(instname, 'gromacs::g_rama')
            out.addConnection('self:ext_in.confs[%d][%d].conf'%(i,j), 
                              '%s:in.traj'%instname)
            out.addConnection('self:ext_in.tpr', '%s:in.tpr'%instname)
            out.addConnection('%s:out.xvg'%instname, 
                              'self:ext_out.xvgs[%d][%d]'%(i,j))
            insts[i] += 1
    pers.set('insts', insts)
    pers.write()

# read the input data
inf=StringIO()
inf.write(sys.stdin.read())
inf.seek(0)
sys.stderr.write("\n-----> Starting\n")
inf.seek(0)
inp=cpc.dataflow.readInput(inf)

if inp.testing():
    # TODO: make it possible for sub-functions to be checked now.
    cpc.util.plugin.testCommand("g_rama -version")
    # try to import msmproject and thereby msmbuilder
    sys.exit(0)



# prepare the output data
out=inp.getFunctionOutput()

g_rama_multi(inp, out)

out.writeXML(sys.stdout)
#sys.stderr.write('\n')
#out.writeXML(sys.stderr)
#sys.stderr.write('\n')
sys.stderr.write("-----> Finished.\n")


