#!/usr/bin/env python

# This file is part of Copernicus
# http://www.copernicus-computing.org/
# 
# Copyright (C) 2011, Sander Pronk, Iman Pouya, Erik Lindahl, and others.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published 
# by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import sys
import os
import math
import os.path
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

import cpc.dataflow
from cpc.dataflow import StringValue
from cpc.dataflow import FloatValue
from cpc.dataflow import IntValue
from cpc.dataflow import FileValue
from cpc.dataflow import RecordValue
from cpc.dataflow import ArrayValue

import reparametrize


class FEError(cpc.dataflow.ApplicationError):
    pass


def rep(inp, out):
    diheds=inp.getInput('dihedrals')
    ndx_file=inp.getInput('res_index')
    start_conf=inp.getInput('start_conf')
    start_xvg=inp.getInput('start_xvg')
    end_conf=inp.getInput('end_conf')
    end_xvg=inp.getInput('end_xvg')
    Nswarms=inp.getInput('Nswarms')
    Ninterpolants=inp.getInput('Ninterpolants')
    Nchains=inp.getInput('Nchains')
    # create a python object from the xvg_array_array
    dihedrals=[]
    for i in range(len(diheds)):
        dih_i=[]
        xvgs=inp.getInput('dihedrals[%d]'%i)
        for j in range(len(xvgs)):
            xvg=inp.getInput('dihedrals[%d][%d]'%(i,j))
            if xvg is not None:
                dih_i.append(inp.getInput('dihedrals[%d][%d]'%(i,j)))
            else:
                sys.stderr.write('Swarm trajectory %d %d failed\n'%(i,j))
                sys.stderr.write('The xvg is: %s %s\n'%(xvg,FileValue(xvg)))
        dihedrals.append(dih_i)
    # call the external python script
    top=inp.getInput('path[0].top')
    includes=[]
    path=inp.getInput('path')
    for i in range(len(path)):
        inc_array=inp.getInput('path[%d].include'%i)
        if inc_array is not None:
            subincludes=[]
            for j in range(len(inc_array)):
                inc_ij=inp.getInput('path[%d].include[%d]'%(i,j))
                subincludes.append(inc_ij)
            includes+=[subincludes]
    # TODO get previous path points and measure distance of displacment 
    reparametrize.reparametrize(dihedrals, ndx_file, start_conf, start_xvg, end_conf, end_xvg, top, includes)
    conf_path=inp.getInput('path')
    confs=inp.getInput('restrained_confs')
    for i in range(len(conf_path)):
        top=FileValue(inp.getInput('path[%d].top'%i))
        out.setOut('path[%d].top'%i,top)
        conf=FileValue(inp.getInput('restrained_confs[%d]'%i))
        out.setOut('path[%d].conf'%i,conf)
        # connect the reparametrized includes
        for j in range(Nchains):
            include=os.path.join(inp.getOutputDir(),'dihre_%d_chain_%d.itp'%(i+1,j))
            out.setOut('path[%d].include[%d]'%(i,j),FileValue(include))
        # connect any additional include files
        if len(includes[0])>Nchains:
            for j in range(Nchains,len(includes[0])):
                include=inp.getInput('path[%d].include[%d]'%(i,j))
                out.setOut('path[%d].include[%d]'%(i,j),FileValue(include))


# read the input data
inf=StringIO()
inf.write(sys.stdin.read())
inf.seek(0)
sys.stderr.write("\n-----> Starting\n")
inf.seek(0)
inp=cpc.dataflow.readInput(inf)

if inp.testing():
    # TODO: make it possible for sub-functions to be checked now.
    cpc.util.plugin.testCommand("g_bar -version")
    cpc.util.plugin.testCommand("grompp -version")
    cpc.util.plugin.testCommand("trjconv -version")
    cpc.util.plugin.testCommand("gmxdump -version")
    # try to import msmproject and thereby msmbuilder
    sys.exit(0)



# prepare the output data
out=inp.getFunctionOutput()

rep(inp, out)

out.writeXML(sys.stdout)
#sys.stderr.write('\n')
#out.writeXML(sys.stderr)
#sys.stderr.write('\n')
sys.stderr.write("-----> Finished.\n")


