#!/usr/bin/env python

# This file is part of Copernicus
# http://www.copernicus-computing.org/
# 
# Copyright (C) 2011, Sander Pronk, Iman Pouya, Erik Lindahl, and others.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published 
# by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import sys
import os
import math
import os.path
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

import cpc.dataflow
from cpc.dataflow import StringValue
from cpc.dataflow import FloatValue
from cpc.dataflow import IntValue
from cpc.dataflow import RecordValue
from cpc.dataflow import ArrayValue
from cpc.dataflow import FileValue

class FEError(cpc.dataflow.ApplicationError):
    pass


def run(inp, out):
    pers=cpc.dataflow.Persistence(os.path.join(inp.persistentDir,
                                               "persistent.dat"))

    # first create the right mdp file
    # dihedral restraints are on
    merge=pers.get('merge')
    if merge is None or merge==0:
        merge=1
        out.addInstance('merge', 'gromacs::merge_mdp')
        out.addConnection('self:ext_in.grompp.mdp', 'merge:in.mdp')
        out.addConnection('self:ext_in.grompp.settings', 'merge:in.settings')
        # the following settings are standardized for the swarms method calculation
        # dihedral restraints are necessary, but the other settings are flexible 
        tol=inp.getInput('em_tolerance')
        settings=[]
        settings.append(RecordValue( { 'name' : StringValue('dihre'),
                                       'value' : StringValue('yes') } ) )
        settings.append(RecordValue( { 'name' : StringValue('integrator'),
                                       'value' : StringValue('steep') } ) )
        settings.append(RecordValue( { 'name' : StringValue('emtol'),
                                       'value' : StringValue("%g"%tol) } ) )
        settings.append(RecordValue( { 'name' : StringValue('nsteps'),
                                       'value' : StringValue('20000') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstxout'),
                                       'value' : StringValue('0') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstvout'),
                                       'value' : StringValue('0') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstfout'),
                                       'value' : StringValue('0') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstlog'),
                                       'value' : StringValue('10000') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstenergy'),
                                       'value' : StringValue('120') } ) )
        out.setSubOut('minimization_settings', ArrayValue(settings))
    pers.set('merge', merge)

    mdruns=pers.get('mdruns')
    if mdruns is None and mdruns<1:
        out.addInstance('runs', 'gromacs::grompp_mdrun_multi')
        out.addConnection('self:ext_in.grompp.ndx', 'runs:in.ndx[0]')
        out.addConnection('self:ext_in.grompp.mdrun_cmdline_options',
                          'runs:in.cmdline_options[0]')
        # connect the resources from the tuning run
        out.addConnection('self:ext_in.resources', 'runs:in.resources[0]')
        # connect the mdp setting specified above
        out.addConnection('merge:out.mdp', 'runs:in.mdp[0]')
        out.addConnection('self:sub_out.minimization_settings', 
                          'runs:in.settings[0]')
        # connection from the sub-network of input configurations to the runs 
        out.addConnection('self:sub_out.confs', 'runs:in.conf')
        out.addConnection('self:sub_out.tops', 'runs:in.top')
        out.addConnection('self:sub_out.includes', 'runs:in.include')
        out.addConnection('runs:out.conf', 'self:sub_in.confs')

        # create the input objects for the minimization runs
        in_confs=inp.getInput('conf_path')
        for i in range(len(in_confs)):
            conf=inp.getInput('conf_path[%d].conf'%i)
            top=inp.getInput('conf_path[%d].top'%i)
            include=inp.getInput('conf_path[%d].include'%i)
            out.setSubOut('confs[%d]'%i, FileValue(conf))
            out.setSubOut('tops[%d]'%i, FileValue(top))
            out.setSubOut('includes[%d]'%i, ArrayValue(include))
            # The topologies do not change
            out.setOut('minimized_conf_path[%d].top'%i, FileValue(top))
            out.setOut('minimized_conf_path[%d].include'%i, ArrayValue(include))
        mdruns=1
    pers.set('mdruns', mdruns)

    # ensure that the minimization has completed
    # TODO instead use a complete type
    confs=inp.getSubnetInput('confs')
    if confs is not None and len(confs) > 0:
        for i in range(len(confs)):
            conf=inp.getSubnetInputValue('confs[%d]'%i)
            if conf.value is not None and conf.isUpdated():
                out.setOut('minimized_conf_path[%d].conf'%i, conf)
    pers.write()

# read the input data
inf=StringIO()
inf.write(sys.stdin.read())
inf.seek(0)
sys.stderr.write("\n-----> Starting\n")
inf.seek(0)
inp=cpc.dataflow.readInput(inf)

if inp.testing():
    # TODO: make it possible for sub-functions to be checked now.
    cpc.util.plugin.testCommand("g_bar -version")
    cpc.util.plugin.testCommand("grompp -version")
    cpc.util.plugin.testCommand("trjconv -version")
    cpc.util.plugin.testCommand("gmxdump -version")
    # try to import msmproject and thereby msmbuilder
    sys.exit(0)



# prepare the output data
out=inp.getFunctionOutput()

run(inp, out)

out.writeXML(sys.stdout)
#sys.stderr.write('\n')
#out.writeXML(sys.stderr)
#sys.stderr.write('\n')
sys.stderr.write("-----> Finished.\n")


