#!/usr/bin/env python

# This file is part of Copernicus
# http://www.copernicus-computing.org/
# 
# Copyright (C) 2011, Sander Pronk, Iman Pouya, Erik Lindahl, and others.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as published 
# by the Free Software Foundation
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


import sys
import os
import math
import os.path
try:
    from cStringIO import StringIO
except ImportError:
    from StringIO import StringIO

import cpc.dataflow
from cpc.dataflow import StringValue
from cpc.dataflow import FloatValue
from cpc.dataflow import IntValue
from cpc.dataflow import RecordValue
from cpc.dataflow import ArrayValue
from cpc.dataflow import FileValue

class FEError(cpc.dataflow.ApplicationError):
    pass

# thermalize the system and relax it with the new constaints
# short integration timestep is employed to properly evolve the
# initially unstable system

def run(inp, out):
    pers=cpc.dataflow.Persistence(os.path.join(inp.getPersistentDir(),
                                               "persistent.dat"))

    # first create the right mdp file
    merge=pers.get('merge')
    if merge is None and merge!=1:
        merge=1
        out.addInstance('merge', 'gromacs::merge_mdp')
        out.addConnection('self:ext_in.grompp.mdp', 'merge:in.mdp')
        out.addConnection('self:ext_in.grompp.settings', 'merge:in.settings')
        # thermalize for 5000 steps
        settings=[] 
        settings.append(RecordValue( { 'name' : StringValue('dihre'),
                                       'value' : StringValue('yes') } ) )
        settings.append(RecordValue( { 'name' : StringValue('dihrefc'),
                                       'value' : StringValue('100') } ) )
        settings.append(RecordValue( { 'name' : StringValue('integrator'),
                                       'value' : StringValue('sd') } ) )
        settings.append(RecordValue( { 'name' : StringValue('dt'),
                                       'value' : StringValue('0.0005') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nsteps'),
                                       'value' : StringValue('5000') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstfout'),
                                       'value' : StringValue('0') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstxtcout'),
                                       'value' : StringValue('0') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstlog'),
                                       'value' : StringValue('10000') } ) )
        settings.append(RecordValue( { 'name' : StringValue('nstenergy'),
                                       'value' : StringValue('120') } ) )
        out.setSubOut('restrained_settings', ArrayValue(settings))
    pers.set('merge', merge)

    mdruns=pers.get('mdruns')
    if mdruns is None and mdruns!=1:
        out.addInstance('runs', 'gromacs::grompp_mdrun_multi')
        out.addConnection('self:ext_in.grompp.ndx', 'runs:in.ndx[0]')
        out.addConnection('self:ext_in.grompp.mdrun_cmdline_options',
                          'runs:in.cmdline_options[0]')
        out.addConnection('self:ext_in.resources', 'runs:in.resources[0]')
        out.addConnection('merge:out.mdp', 'runs:in.mdp[0]')
        out.addConnection('self:sub_out.restrained_settings', 
                          'runs:in.settings[0]')
        #out.addConnection('runs:out.trr', 'self:sub_in.trrs')

        # create the include array array
        in_confs=inp.getInput('path')
        for i in range(len(in_confs)):
            outconf=inp.getOutput
            out.addConnection('self:ext_in.path[%d].conf'%i,'runs:in.conf[%d]'%i)
            out.addConnection('self:ext_in.path[%d].top'%i,'runs:in.top[%d]'%i)
            out.addConnection('self:ext_in.path[%d].include'%i,'runs:in.include[%d]'%i)
            out.addConnection('runs:out.conf[%d]'%i, 'self:ext_out.confs[%d]'%i)
            out.addConnection('self:ext_in.path[%d].top'%i,'self:ext_out.path[%d].top'%i)

            out.addConnection('self:ext_in.path[%d].include'%i,'self:ext_out.path[%d].include'%i)


        mdruns=1
    pers.set('mdruns', mdruns)

    pers.write()

# read the input data
inf=StringIO()
inf.write(sys.stdin.read())
inf.seek(0)
sys.stderr.write("\n-----> Starting\n")
inf.seek(0)
inp=cpc.dataflow.readInput(inf)

if inp.testing():
    # TODO: make it possible for sub-functions to be checked now.
    cpc.util.plugin.testCommand("g_bar -version")
    cpc.util.plugin.testCommand("grompp -version")
    cpc.util.plugin.testCommand("trjconv -version")
    cpc.util.plugin.testCommand("gmxdump -version")
    # try to import msmproject and thereby msmbuilder
    sys.exit(0)



# prepare the output data
out=inp.getFunctionOutput()

run(inp, out)

out.writeXML(sys.stdout)
#sys.stderr.write('\n')
#out.writeXML(sys.stderr)
#sys.stderr.write('\n')
sys.stderr.write("-----> Finished.\n")


