#!/bin/sh


# start the project
cpcc -c client.cnx start mdrun_test
# import the gromacs module with grompp and mdrun functions
cpcc -c client.cnx  import gromacs
# add the grompp and mdrun function instances
cpcc -c client.cnx  instance gromacs::grompp grompp
cpcc -c client.cnx  instance gromacs::mdrun mdrun
# connect the tpr output of grompp to the tpr input of mdrun
cpcc connect grompp:out.tpr mdrun:in.tpr
# set the grompp inputs
cpcc -c client.cnx  set-file grompp:in.conf examples/mdrun-test/conf.gro
cpcc -c client.cnx  set-file grompp:in.mdp  examples/mdrun-test/grompp.mdp
cpcc -c client.cnx  set-file grompp:in.top  examples/mdrun-test/topol.top
# 
cpcc -c client.cnx  set grompp:in.settings[0].name nsteps
cpcc -c client.cnx  set grompp:in.settings[0].value 12500
cpcc -c client.cnx  set grompp:in.settings[1].name integrator
cpcc -c client.cnx  set grompp:in.settings[1].value md
# and activate
cpcc -c client.cnx activate


