#!/bin/sh


./cpc-server -c ~/.cpc/test/0/ start
./cpc-server -c ~/.cpc/test/1/ start
./cpc-server -c ~/.cpc/test/3/ start
./cpc-server -c ~/.cpc/test/4/ start
./cpc-server -c ~/.cpc/test/2/ start -d

 
